# Generated by Django 4.2.7 on 2023-11-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='created_by',
            field=models.CharField(max_length=150),
        ),
    ]
