# Generated by Django 4.2.7 on 2023-11-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
