# Generated by Django 4.2.7 on 2023-11-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_homework_image_user_avatar_alter_dohomework_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='image',
            field=models.ImageField(blank=True, default='static/images/thump-1.png', null=True, upload_to='app/static/uploads/homework'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/pic-1.jpg', null=True, upload_to='app/static/uploads/avatar'),
        ),
    ]
