# Generated by Django 4.2.7 on 2023-11-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_homework_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, default='fmRBApAw3mCUMNQCrBWjgR', max_length=20, null=True),
        ),
    ]
