# Generated by Django 4.2.7 on 2023-11-16 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_class_invite_code_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='app.user'),
        ),
        migrations.AlterField(
            model_name='class',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='app.user'),
        ),
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, default='9ZDYMzhC4hTFMhW2QyzVN5', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dohomework',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dohomeworks', to='app.homework'),
        ),
        migrations.AlterField(
            model_name='dohomework',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dohomeworks', to='app.user'),
        ),
        migrations.CreateModel(
            name='User_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_classes', to='app.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_classes', to='app.user')),
            ],
        ),
    ]
