# Generated by Django 4.2.7 on 2023-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_class_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/uploads/attendance'),
        ),
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, default='ChvZsf83Xo7opgSBP3TYF9', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dohomework',
            name='file',
            field=models.FileField(upload_to='static/uploads/homework'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/homework'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='image',
            field=models.ImageField(blank=True, default='static/images/thump-1.png', null=True, upload_to='static/uploads/homework'),
        ),
    ]
