# Generated by Django 4.2.7 on 2023-11-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_attendance_image_alter_class_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, default='MTkjm6kRN8UNqTdYdjrX24', max_length=30, null=True),
        ),
    ]
