# Generated by Django 4.2.7 on 2023-11-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_class_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, default='static/images/thump-1.png', null=True, upload_to='static/uploads/class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, default='36kJCNxpoUcbs2fsEXxFMc', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='image',
            field=models.ImageField(blank=True, default='static/images/thump-2.png', null=True, upload_to='static/uploads/homework'),
        ),
    ]
