# Generated by Django 4.2.7 on 2023-11-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_class_image_alter_class_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, default='thumb-1.png', null=True, upload_to='static/uploads/class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, default='XVa4VY3eoJ8i8iwx5oDm9h', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='image',
            field=models.ImageField(blank=True, default='thumb-2.png', null=True, upload_to='static/uploads/homework'),
        ),
    ]
