# Generated by Django 4.2.7 on 2023-11-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_class_image_alter_class_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, default='GWA2qMH4gKhmkzq4HHuNna', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/homework'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/uploads/avatar'),
        ),
    ]
