# Generated by Django 4.2.7 on 2023-11-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_dohomework_created_at_homework_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, default='hG6J8stLyQ6miZzPHtp9n3', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
