# Generated by Django 4.2.7 on 2023-11-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_class_invite_code_alter_homework_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, default='Nagn5BwmrQ9P24FBYNMhvc', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
