# Generated by Django 4.2.7 on 2023-11-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_class_invite_code_alter_homework_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, default='adACLx4F9eQrciLYUxr9u4', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dohomework',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
