# Generated by Django 4.2.7 on 2023-11-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_class_invite_code_alter_dohomework_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, default='fnBicv3hqPXTbXFHZYDT3L', max_length=30, null=True),
        ),
    ]
