# Generated by Django 4.2.7 on 2023-11-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_class_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, default='cyuyrXELkcnT6S8Q7qCq5P', max_length=30, null=True),
        ),
    ]
