# Generated by Django 4.2.7 on 2023-11-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_class_invite_code_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, default='S9E9pEciV7AAdfhWaHFzQp', max_length=30, null=True),
        ),
    ]
